[versions]
google-play-services-ads = "23.1.0"
robolectric = "4.3.1"

[libraries]
google-play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "google-play-services-ads" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
shadows-httpclient = { module = "org.robolectric:shadows-httpclient", version.ref = "robolectric" }
